class Solution {
    public:
        vector<vector<int>> threeSum(vector<int>& nums) {
                //sort
                        sort(nums.begin(), nums.end());
                                vector<vector<int>> triplets;
                                        for(int i=0; i < nums.size()-2; i++){
                                                    if(i-1 >=0 && nums[i] == nums[i-1]) continue;
                                                                int target = nums[i] * (-1);
                                                                            int left = i + 1;
                                                                                        int right = nums.size()-1;
                                                                                                    while(left < right){
                                                                                                                    int sum = nums[left] + nums[right];
                                                                                                                                    if(sum == target){
                                                                                                                                                        vector<int> triplet(3);
                                                                                                                                                                            triplet[0] = nums[i];
                                                                                                                                                                                                triplet[1] = nums[left];
                                                                                                                                                                                                                    triplet[2] = nums[right];
                                                                                                                                                                                                                                        triplets.push_back(triplet);
                                                                                                                                                                                                                                                            left++;
                                                                                                                                                                                                                                                                                right--;
                                                                                                                                                                                                                                                                                                    while(left < right && nums[left] == nums[left-1]){
                                                                                                                                                                                                                                                                                                                            left++;
                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                    while(left < right && nums[right] == nums[right+1]){
                                                                                                                                                                                                                                                                                                                                                                                            right--;
                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                else if(sum < target){
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    left++;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        while(left < right && nums[left] == nums[left-1]){
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                left++;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }                                   
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    else{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            right--;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                while(left < right && nums[right] == nums[right+1]){
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        right--;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return triplets;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    //Trigger:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    //Find three elements with a target sum + array can be sorted ----->>>>>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    //Fix one element and use two pointers
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    //Last solved on: 27 Sept 2026
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    //Last solved in: 30 mins
}